server:
  port: 8080
spring:
  application:
    name: greetingservice
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: perf
management:
  endpoints:
    web:
      exposure:
        include:
        - refresh
#        - '*'
greetingservice:
  greeting: "Olá"
  default-value: "Mundo!"
